"""Reduced Pydantic schema for LLM-only text fields."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class AITextRecommendation(BaseModel):
    """LLM-only output — only subjective text fields.

    All technical fields are generated by the backend rule engine.
    """

    model_config = ConfigDict(extra="forbid")

    summary: str = Field(
        description="One-sentence verdict for the track pair. Max 25 words."
    )
    mix_direction: str = Field(
        description=(
            "High-level mixing direction (blend, cut, bridge, etc.). Max 20 words."
        )
    )
    club_tip: str = Field(
        default="",
        description="Practical club or performance tip. Max 20 words.",
    )
    professional_notes: str = Field(
        default="",
        description="Additional professional observations. Max 30 words.",
    )
    confidence: int = Field(
        default=50,
        ge=0,
        le=100,
        description="Confidence score from 0 to 100.",
    )
